version: '3.8'

services:
  test.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: test.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongP@ss!
      
  api:
    build:
      context: ./src/ArcadeStore.Api
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    depends_on:
      - test.db
    environment:
      ConnectionStrings__Default: "Server=test.db;Database=ArcadeStoreDb;User Id=sa;Password=YourStrongP@ss!;"